platform :ios, '17.6'

project 'App.xcodeproj'

target 'App' do
  use_frameworks!

  # Tencent Cloud TRTC native SDK. Install with:
  #   sudo gem install cocoapods
  #   pod install
  #
  # After installation, open App.xcworkspace instead of App.xcodeproj.
  pod 'TXLiteAVSDK_TRTC'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.6'
    end
  end
end
